### ISSUE TITLE
A records (ALIAS) to ELBs on a different AWS account are unconfigurable

### ISSUE THREAD

**Issue by bwalding** [winebarrel/roadworker#10]
We have a zone apex record that needs to point to an ELB on another account (that we do not control or have credentials for).

The way `route53-ext` resolves ELBs does not handle this case, and we end up receiving the "Cannot find ELB" error due to this (which breaks the DNS update).

I can see two obvious solutions
a) fix the root cause (I tried monkeypatching around it, but was unsuccessful)
b) provide a way to tell roadworker to ignore a given record - in this case I would just leave the ALIAS record in Route 53, and roadworker would be told to just ignore it when generating the change list / applying change list.

**Comment by yteraoka** [comment]
I sent related pull request. Please check https://github.com/winebarrel/roadworker/pull/21

**Comment by winebarrel** [comment]
Thanks! Please wait..

**Comment by limitusus** [comment]
Hello,

Is it resolved?
It seems resolved but on my environment it fails, even when I specify `:hosted_zone_id`.

```
[ERROR] RuntimeError: Cannot find ELB: XXXXX.ap-northeast-1.elb.amazonaws.com
```

To know why I inserted `p dns_name_opts` here (https://github.com/winebarrel/roadworker/blob/0.5.5/lib/roadworker/route53-wrapper.rb#L175) but written was only `{:evaluate_target_health=>false}`.
When I also specified `:evaluate_target_health => true`, it was in effect: `{:evaluate_target_health=>true}`.
I think I should conclude somehow the `hosted_zone_id` is not properly passed to `Aws::Route53.dns_name_to_alias_target` via `dns_name_opts`.

I think I should write the resource record like this (https://github.com/winebarrel/roadworker/blob/v0.5.6/spec/roadworker_create_spec.rb#L171), but is it wrong?

**Comment by winebarrel** [comment]
@limitusus Thank you for your report :smiley: 
Will investigate it on the weekend.

**Comment by limitusus** [comment]
Hi @winebarrel,
Is there any progress on it?

**Comment by winebarrel** [comment]
Sorry untouched...

**Comment by hunginday** [comment]
Hi all, is this problem fixed? I still see this issue in my current version of roadworker (roadwork 0.5.6).
Could you please take a look at this?

**Comment by winebarrel** [comment]
Sorry, this issue information is not enough to solve this problem 😢 
Please tell me the following information.

- Ruby version
- Roadworker version
- Routefile DSL
- backtrace (pass `--debug` option)
- AWS_REGION/AWS_DEFAULT_REGION env val

(Please contact @sgwr_dts (twitter) if you can speak Japanese)

**Comment by limitusus** [comment]
I tested under the following conditions (hid ELB name; it's a production data):

`ruby -v`: `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]`
`roadwork -v`: `roadwork 0.5.6`
Routefile (part/changed name):
```
hosted zone "limitusus.info." do
  (snip)
  rrset "xxx.limitusus.info.", 'A' do
    dns_name "dualstack.xxx.yyy.zzz-0000000000.ap-northeast-1.elb.amazonaws.com."
  end
end
```

Backtrace:
```
/home/limit/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roadworker-0.5.6/lib/roadworker/route53-ext.rb:82:in `elb_dns_name_to_alias_target': Cannot find ELB: dualstack.xxx.yyy.zzz-0000000000.ap-northeast-1.elb.amazonaws.com (RuntimeError)
	from /home/limit/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roadworker-0.5.6/lib/roadworker/route53-ext.rb:43:in `dns_name_to_alias_target'
	from /home/limit/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roadworker-0.5.6/lib/roadworker/route53-wrapper.rb:176:in `block in create'
	from /home/limit/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roadworker-0.5.6/lib/roadworker/route53-wrapper.rb:168:in `each'
	from /home/limit/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roadworker-0.5.6/lib/roadworker/route53-wrapper.rb:168:in `create'
	from /home/limit/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roadworker-0.5.6/lib/roadworker/client.rb:130:in `block in walk_rrsets'
	from /home/limit/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roadworker-0.5.6/lib/roadworker/client.rb:113:in `each'
	from /home/limit/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roadworker-0.5.6/lib/roadworker/client.rb:113:in `walk_rrsets'
	from /home/limit/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roadworker-0.5.6/lib/roadworker/client.rb:76:in `block in walk_hosted_zones'
	from /home/limit/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roadworker-0.5.6/lib/roadworker/client.rb:69:in `each'
	from /home/limit/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roadworker-0.5.6/lib/roadworker/client.rb:69:in `walk_hosted_zones'
	from /home/limit/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roadworker-0.5.6/lib/roadworker/client.rb:23:in `apply'
	from /home/limit/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/roadworker-0.5.6/bin/roadwork:180:in `<top (required)>'
	from /home/limit/.rbenv/versions/2.3.1/bin/roadwork:23:in `load'
	from /home/limit/.rbenv/versions/2.3.1/bin/roadwork:23:in `<main>'
```

No env val (I tested it using `--profile=my` option)

Hope it helps

**Comment by hunginday** [comment]
Hi @winebarrel,

It can not create records for ELB that does not belong to different AWS account (not belong to current account).

# ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

# roadwork --version
roadwork 0.5.6

# env val
AWS_REGION/AWS_DEFAULT_REGION are not set

# roadwork -a
Apply `Routefile` to Route53
Create ResourceRecordSet: xxx.com A
[ERROR] RuntimeError: Cannot find ELB: xxx.xxx.elb.amazonaws.com

------------------------
debug details
------------------------
....
[Aws::ElasticLoadBalancing::Client 200 0.493465 0 retries] describe_load_balancers()

/usr/local/app/roadworker/vendor/bundle/ruby/2.3.0/gems/roadworker-0.5.6/lib/roadworker/route53-ext.rb:82:in `elb_dns_name_to_alias_target': Cannot find ELB: xxx.xxx.elb.amazonaws.com (RuntimeError)
	from /usr/local/app/roadworker/vendor/bundle/ruby/2.3.0/gems/roadworker-0.5.6/lib/roadworker/route53-ext.rb:43:in `dns_name_to_alias_target'
	from /usr/local/app/roadworker/vendor/bundle/ruby/2.3.0/gems/roadworker-0.5.6/lib/roadworker/route53-wrapper.rb:176:in `block in create'
	from /usr/local/app/roadworker/vendor/bundle/ruby/2.3.0/gems/roadworker-0.5.6/lib/roadworker/route53-wrapper.rb:168:in `each'
	from /usr/local/app/roadworker/vendor/bundle/ruby/2.3.0/gems/roadworker-0.5.6/lib/roadworker/route53-wrapper.rb:168:in `create'
	from /usr/local/app/roadworker/vendor/bundle/ruby/2.3.0/gems/roadworker-0.5.6/lib/roadworker/client.rb:130:in `block in walk_rrsets'
	from /usr/local/app/roadworker/vendor/bundle/ruby/2.3.0/gems/roadworker-0.5.6/lib/roadworker/client.rb:113:in `each'
	from /usr/local/app/roadworker/vendor/bundle/ruby/2.3.0/gems/roadworker-0.5.6/lib/roadworker/client.rb:113:in `walk_rrsets'
	from /usr/local/app/roadworker/vendor/bundle/ruby/2.3.0/gems/roadworker-0.5.6/lib/roadworker/client.rb:76:in `block in walk_hosted_zones'
	from /usr/local/app/roadworker/vendor/bundle/ruby/2.3.0/gems/roadworker-0.5.6/lib/roadworker/client.rb:69:in `each'
	from /usr/local/app/roadworker/vendor/bundle/ruby/2.3.0/gems/roadworker-0.5.6/lib/roadworker/client.rb:69:in `walk_hosted_zones'
	from /usr/local/app/roadworker/vendor/bundle/ruby/2.3.0/gems/roadworker-0.5.6/lib/roadworker/client.rb:23:in `apply'
	from /usr/local/app/roadworker/vendor/bundle/ruby/2.3.0/gems/roadworker-0.5.6/bin/roadwork:180:in `<top (required)>'
	from /usr/local/bin/roadwork:17:in `load'
	from /usr/local/bin/roadwork:17:in `<main>'

**Comment by winebarrel** [comment]
Thanks for reporst!
I'm sorry investigation is delayed.

**Comment by winebarrel** [comment]
I think I fix the problem. probably...
Please try [v0.5.7.beta](https://rubygems.org/gems/roadworker/versions/0.5.7.beta).

**Comment by hunginday** [comment]
@winebarrel,

Thanks a lot, it seems fixed!!

**Comment by limitusus** [comment]
It worked for me too. Thanks!
