### ISSUE TITLE
Any way to export same domain name / different type hosted zone with the split option?

### ISSUE THREAD

**Issue by orih** [winebarrel/roadworker#22]
I just have a quick question.

#### Hosted Zones

Domain Name | Type
------------ | -------------
example.com | Public
example.com | Private

#### Command

```
$ roadwork -e -o Routefile --split
```

The command above exported `Routefile` and **one** `example.com.route` file.

#### Routefile

```
# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'example.com.route'
require 'example.com.route'
```

#### example.com.route

```
# -*- mode: ruby -*-
# vi: set ft=ruby :
hosted_zone "example.com." do
  vpc "region", "vpc-id"

  some private hosted zone's records...
end
```

I guess the `example.com.route` file for private hosted zone's overwrote the public one.

Are there any workaround?

**Comment by winebarrel** [comment]
Please use [v0.5.5.beta5](https://rubygems.org/gems/roadworker/versions/0.5.5.beta5)

**Comment by orih** [comment]
Thank you for quick reply!
I'll try it :)

**Comment by winebarrel** [comment]
:smiley:

**Comment by orih** [comment]
It works, thanks for helping me :ok_woman:
