### ISSUE TITLE
Feature request: Flag to disable testing?

### ISSUE THREAD

**Issue by hngkr** [winebarrel/roadworker#35]
Hi,

I would like to kindly propose a feature request for Roadworker.

I would like to use Roadworker to do backup of Route53 from an AWS Lambda function, and I have gotten Roadworker to load (using Traveling Ruby and by following [these instructions](http://www.adomokos.com/2016/06/using-ruby-in-aws-lambda.html)). So far, so good.

However, I wasn't aware that it's not possible to use UDP from within the Lambda environment, and that Roadworker seems to do that. Which leaves me with a stacktrace that looks like below:

`
/var/task/lib/vendor/ruby/2.2.0/gems/roadworker-0.5.6/lib/roadworker/dsl-tester.rb:12:in``initialize': Operation not permitted - socket(2) - udp (Errno::EPERM)
    from /var/task/lib/vendor/ruby/2.2.0/gems/roadworker-0.5.6/lib/roadworker/dsl-tester.rb:12:in``new'
    from /var/task/lib/vendor/ruby/2.2.0/gems/roadworker-0.5.6/lib/roadworker/dsl-tester.rb:12:in``block in <top (required)>'
    from /var/task/lib/vendor/ruby/2.2.0/gems/roadworker-0.5.6/lib/roadworker/dsl-tester.rb:20:in``call'
    from /var/task/lib/vendor/ruby/2.2.0/gems/roadworker-0.5.6/lib/roadworker/dsl-tester.rb:20:in``<top (required)>'
    from /var/task/lib/vendor/ruby/2.2.0/gems/roadworker-0.5.6/lib/roadworker.rb:24:in`require'
    from /var/task/lib/vendor/ruby/2.2.0/gems/roadworker-0.5.6/lib/roadworker.rb:24:in `<top (required)>'
    from /var/task/lib/vendor/ruby/2.2.0/gems/roadworker-0.5.6/bin/roadwork:4:in`require'
    from /var/task/lib/vendor/ruby/2.2.0/gems/roadworker-0.5.6/bin/roadwork:4:in `<top (required)>'
    from /var/task/lib/vendor/ruby/2.2.0/bin/roadwork:23:in`load'
    from /var/task/lib/vendor/ruby/2.2.0/bin/roadwork:23:in `<main>'
`

I believe that having a flag that disables testing (or don't open a UDP socket in dsl-tester.rb when testing isn't specified) might enable Roadworker to be used from within Lambda -- which is a pretty sweet use case nowadays.

It's probably not too complicated to implement, but with regards to Ruby, I'm very much a simpleton. It's not likely that I can do a PR in a clean, idiomatic way.

Thanks in advance.

/ Henning

**Comment by winebarrel** [comment]
Hi, thanks for your report 😃 

I fixed this issue ( https://github.com/winebarrel/roadworker/issues/36 ).
Please try [v0.5.6.beta3](https://rubygems.org/gems/roadworker/versions/0.5.7.beta3).

**Comment by hngkr** [comment]
Just wanted to leave a big Thank You! note and let you know that my experiments with running Roadworker in AWS Lambda actually were quite succesful.

Link to blogpost describing how to do it: https://dashsoft.dk/da/blog/Route53_Lambda_Backups/
