### ISSUE TITLE
v0.5.7 is still in beta?

### ISSUE THREAD

**Issue by takus** [winebarrel/roadworker#37]
Hi,

It seems that v0.5.7 is still in beta release. Do you have any concerns about v0.5.7.beta3? I'd like to manage ALB records by Roadworker, but it is not supported in v0.5.6. 

```
$ bundle exec roadwork -a
[ERROR] RuntimeError: Cannot find ELB: dualstack.xxx.ap-northeast-1.elb.amazonaws.com
```

**Comment by winebarrel** [comment]
v0.5.7 has been released! 😃

**Comment by takus** [comment]
Thank you 👍
