### ISSUE TITLE
複数Hostedzoneの時のapply

### ISSUE THREAD

**Issue by hrix** [winebarrel/roadworker#41]
使い方に関して教えてください
複数管理しているドメインのうち、一つだけをapplyするときに--target-zone をREGEXP記述すると
No change
となって、更新にならないのですが--target-zoneのドメインをREGEXP記述ではなく""で囲って書けば実行できました。
※exportの際はREGEXPでも""でもOKでした
今後は""の記述に統一したほうが良いでしょうか？

**Comment by winebarrel** [comment]
正規表現を見ないと何ともいえないですね、、
実際に実行したコマンドライン上のテキストを教えていただけますか？
また、「"」の解釈はシェルによって異なりそうなので、実行したシェルまで教えていただけると助かります。

**Comment by hrix** [comment]
同じ正規表現でもExportはOK
```
roadwork -e --target-zone ^jobless\.jp\.$ -o Routefile
```
Routefileを変更してapplyしようとすると
```
roadwork -a --target-zone ^jobless\.jp\.$ --dry-run --debug
略
[Aws::Route53::Client 200 0.173624 0 retries] list_hosted_zones()  
No change
```
となります。
"jobless.jp"だとうまく行きます※jobless.jpは架空（実際のものを少しいじってます）

**Comment by winebarrel** [comment]
情報有り難うございます。

これは、hosted_zone名を正規化（末尾の「.」を無視している）ことによるバグですね。
すみません。

apply時に`^jobless\.jp\.$`にマッチしないのは末尾の「.」のためで、さしあたってのワークアラウンドとしては`^jobless\.jp\.?$`、という正規表現にすると、exportでもapplyでもマッチするかと。

`"jobless.jp"`でうまくうごいたのは、末尾を厳密に指定しない正規表現のためと思われます（だいたいのシェルでは`"jobless.jp"`と渡されても、`jobless.jp`の正規表現として解釈されると思われます）

**Comment by hrix** [comment]
ありがとうございます。すぐに解決できて大変助かりました。
※環境お伝えし忘れました。CentOS7の標準（/bin/bash）でした。
